voxelify:
	mkdir -p tools/bin
	g++ -g -otools/bin/voxelify -std=c++11 tools/voxelify.cpp -I/usr/include -L/usr/lib -llibfreeimage -llibboost_regex -llibboost_system -llibboost_filesystem
   
voxelify-test: voxelify
	tools/bin/voxelify development/models/venusaur/Venusaur.obj 20 ignore/result.png

zip2obj:
	mkdir -p tools/bin
	g++ -g -otools/bin/zip2obj -std=c++11 tools/zip2obj.cpp -I/usr/include -L/usr/lib -llibfreeimage -llibboost_regex -llibboost_system -llibboost_filesystem -lzip